import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import { marked } from 'marked'
import Layout from '../../components/layout'
import Image from 'next/image'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function PostPage(props) {
  const [windowWidth, setWindowWidth] = useState(0)
  const [windowHeigth, setWindowHeigth] = useState(0)
  useEffect(() => {
    setWindowWidth(window.innerWidth)
    setWindowHeigth(window.innerHeight)
  }, [])
  return <>
    <Head>
      <title>{props.frontmatter.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <div className=''>
        <Image width={windowWidth} height={windowHeigth / 2} alt="props.slug" src={props.frontmatter.cover_image} />
        <div className='w-4/5 mx-auto bg-black -translate-y-20 p-3 rounded-lg'>
          <h1 className="text-2xl text-bold">{props.frontmatter.title}</h1>
          <p>{props.frontmatter.description}</p>
          <div dangerouslySetInnerHTML={{ __html: marked(props.content) }}></div>
        </div>
      </div>
    </Layout></>
}

export async function getStaticPaths() {
  const files = fs.readdirSync(path.join('posts'))
  const paths = files.map(filename => ({
    params: {
      slug: filename.replace('.md', '')
    }
  }))

  return {
    paths,
    fallback: false
  }
}

export async function getStaticProps({ params: { slug } }) {
  const markdownWithMeta = fs.readFileSync(path.join('posts', slug + '.md'))

  const { data: frontmatter, content } = matter(markdownWithMeta)
  return {
    props: {
      content,
      frontmatter,
      slug
    }
  }
}