import Head from 'next/head'
import CategoryPosts from '../components/category'
import Layout from '../components/layout'
import getAllPosts from '../scripts/getAllPosts'


export default function Home({ posts }) {
  const categories = []
  posts.map((post, indexPost) => {
    const category = post.frontmatter.category
    const findCategory = categories.findIndex(cat => {
      return cat.category == category
    })
    if (findCategory < 0) {
      categories.push({ category, post: [post] })
    } else {
      categories[findCategory] = {
        ...categories[findCategory],
        post: [...categories[findCategory].post, post]
      }
    }
  })
  return (
    <div>
      <Head>
        <title>Simple Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className='flex flex-col'>
          {categories.map(cat => {
            return <CategoryPosts key={cat.category} cat={cat} />
          }
          )}
        </div>
      </Layout>

    </div>
  )
}

export async function getStaticProps() {
  const posts = getAllPosts()
  return {
    props: {
      posts: posts
    }
  }
}