import Head from 'next/head'
import Layout from '../components/layout'
import Post from '../components/post'
import getAllPosts from '../scripts/getAllPosts'


export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>I love cursos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className='flex'>
        {posts.map(post => {
          return <div key={post.slug} className='p-1'>
            <Post post={post} />
            </div>
          }
          )}
          </div>
      </Layout>
      
    </div>
  )
}

export async function getStaticProps() {
  const posts = getAllPosts()
  return {
    props: {
      posts: posts
    }
  }
}